### ISSUE TITLE
libiio

### ISSUE THREAD

**Issue by josvanr** [witty91/gester#2]
Hello! 

I'm trying to use your app with my tablet touchscreen, but I dont seem to have the sys/bus/iio directory on my system (xubuntu 18.04). I installed libiio and some related packages, but I'm not sure if the dir should appear. Did you need to configure libiio manually for the touchscreen?

thnx

**Comment by josvanr** [comment]
hmm i think it is a ubuntu problem..

**Comment by witty91** [comment]
Hi,
sorry that I didn't respond earlier, but I just found this issue today -- apparently I don't get notified automatically about open issues.
A quick check on my notebook (Arch Linux) shows that I do in fact not have libiio installed. Maybe you can find the necessary information somewhere else in /sys? I would suggest having a look around and see what you can find.
